on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12", "14", "15"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run test
      - run: yarn run coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: pipeline
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello tag"
